### ISSUE TITLE
Optional parameter to return to users a raw text file

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-api#21]
Adds an optional parameter to allow the user to request the raw text file with the content of the gazette.

**Comment by daniboy000** [comment]
The request should return only the txt or the txt and link as well?

**Comment by jvanz** [comment]
Yes, the result JSON should contain all the fields we have now AND the whole text. In other words, this optional parameter will add one more field with all the text indexed for the document and all the other fields do not change.

**Comment by sergiomario** [comment]
@daniboy000 and @jvanz 

The following is a suggestion from Arthur. Makes sense?
![txt_qd](https://user-images.githubusercontent.com/2698516/113176988-6fac3700-9223-11eb-9b3d-39d1d679439c.png)

**Comment by daniboy000** [comment]
I have to see the code to check this but everything is new to me so I'll need to check this behavior before answer.

**Comment by jvanz** [comment]
Yes, this is the answer that I was expecting. So, the bigger change will be in the https://github.com/okfn-brasil/querido-diario-data-processing repository. The API just need to add another field in the response json with the URL populated in the index by the data-processing app.

**Comment by jvanz** [comment]
@andreformento is working on this. See pull request linked
