### ISSUE TITLE
Censo API endpoints

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-api#22]
The https://github.com/okfn-brasil/censo-querido-diario has a database that should be available in the API. So, we need to make the database available to the API and create the endpoints.

Suggested implementation:

request:
- query (city's name substring)

response:
- IBGE city ID
- city name
- state
- "access level"
- List of URL where the gazttes are published

request

`GET /cities?query=b[&size=3]`

response
```json
{
    "cities": [
        {
            "territory_id": "2502201",
            "territory_name": "Bom Jesus",
            "state_code": "PB",
            "access_level": "name",
            "source_publisher": ["multi", "value"]
        },
        {
            "territory_id": "4202404",
            "territory_name": "Blumenau",
            "state_code": "SC",
            "access_level": "name",
            "source_publisher": ["multi", "value"]
        },
        {
            "territory_id": "4302303",
            "territory_name": "Bom Jesus",
            "state_code": "RS",
            "access_level": "name",
            "source_publisher": ["multi", "value"]
        }
    ]
}
```

**Comment by jvanz** [comment]
To allow the development of this feature we need to load the data from a database. I just push in another branch a database interface. The branch has a fake database implementation with reads the data from a csv file. Thus, we can test the endpoints added in this issue.

**Comment by andreformento** [comment]
Very nice @jvanz 🤘

**Comment by jvanz** [comment]
I'm working to finish this.
