### ISSUE TITLE
Add `sortby` parameter

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-api#27]
Add an option in the API endpoints to allow the user to define the order of the search results. The API should allow 3 types: relevance (elasticsearch relevance), date by descending and ascending order.

**Comment by jvanz** [comment]
@andreformento don't you want to work on this? :grin:

**Comment by andreformento** [comment]
Yes, I can do this :D

**Comment by andreformento** [comment]
TODO: boost using keywords
