### ISSUE TITLE
Incluir na API parâmetro para busca exata de termos compostos

### ISSUE THREAD

**Issue by nitaibezerra** [okfn-brasil/querido-diario-api#50]
Atualmente as consultas à API utilizando termos compostos por várias palavras (ex.: acesso à informação, dados abertos, diário oficial) retornam também resultados aproximados, ou seja, com documentos contendo apenas uma das palavras, ou com as palavras separadas.

Por exemplo, [esta pesquisa](https://queridodiario.ok.org.br/pesquisa?term=dados%20abertos) pelo termo "dados abertos" retorna documentos contendo apenas "dados", outros contendo apenas "abertos" e outros contendo "dados" e "abertos" porém separados por outras palavras dentro do documento. Dentre os resultados estão alguns documentos que possuem as duas palavras juntas "dados abertos".

Para algumas necessidades é interessante que se possa forçar um resultado 'exato', ou seja, que resulte apenas os documentos contendo as palavras juntas. Caso não exista nenhum documento, a API deve retornar vazio. 

Alguns buscadores, como o Google, utilizam as aspas como delimitador do termo exato. Uma outra opção seria criar um parâmetro booleano (`exact_search`) para isso na API.

**Comment by giuliocc** [comment]
@nitaibezerra feedbacks são bem vindos! Testa aí :)
