### ISSUE TITLE
Download do JSON pela API retorna SOMENTE a primeira página da busca

### ISSUE THREAD

**Issue by Luisa-Coelho** [okfn-brasil/querido-diario-api#60]
**Português**
O teste foi feito utilizando a palavra-chave "rede cegonha" que atualmente retorna 1406 resultados (espelho do Front-end). No entanto, ao realizar o download do JSON na API, o documento somente contém a primeira página de 141 páginas disponíveis na plataforma.
O download foi feito a partir do botão Download e o parâmetro 'size' foi deletado, ou seja, não há máximo de resultados. 
![image](https://github.com/okfn-brasil/querido-diario-api/assets/87907716/3a307227-867c-4ee8-a090-bc5cb1970b2b)

**English**
The test was conducted using the keyword "rede cegonha," which currently returns 1406 results (frontend mirror). However, when downloading the JSON from the API, the document only contains the first page out of 141 pages available on the platform. The download was initiated from the Download button, and the 'size' parameter was deleted, i.e. there is no maximum limit for results.

**Comment by Luisa-Coelho** [comment]
@tigreped @trevineju

**Comment by trevineju** [comment]
Não tenho certeza, mas talvez não pode não colocar nada em "size". Se ele tiver vazio, vai deve preencher automaticamente com o valor padrão, 10. Tenta subir o valor ao invés de não colocar nada. Se ele encontra 1406 resultados, então `size=1410` deve retornar todos os casos.

Experimentei `https://queridodiario.ok.org.br/api/gazettes?querystring=%22rede%20cegonha%22&excerpt_size=250&number_of_excerpts=1&pre_tags=&post_tags=&size=100&sort_by=relevance` (mudando de 10 para 100 ao invés de deixar vazio e deu certo)

**Comment by Luisa-Coelho** [comment]
Legal! Funcionou! Muito obrigada! Tive que fazer 2 buscas, omitindo os 1000 primeiros resultados na segunda.
