### ISSUE TITLE
Migrar o cliente python do elasticsearch para opensearch

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-api#64]
Migrar o cliente python do elasticsearch para opensearch de modo a suportar o novo motor de dados corretamente

**Comment by jvanz** [comment]
@tigreped vc esta trabalhando nisso? Estou perguntando isso só para atualizar o status da issue corretamente. ;)

**Comment by tigreped** [comment]
> @tigreped vc esta trabalhando nisso? Estou perguntando isso só para atualizar o status da issue corretamente. ;)

Idem aqui @jvanz achei que com o merge tinha fechado a issue, deve ter passado. Obrigado!
